### ISSUE TITLE
作者您好，可以看下吗，程序运行到loss_all.backward()有问题

### ISSUE THREAD

**Issue by flow-ljh** [TmacMai/Multimodal-Correlation-Learning#3]
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [40]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by TmacMai** [comment]
请参看https://github.com/TmacMai/Multimodal-Correlation-Learning/issues/1

**Comment by flow-ljh** [comment]
好的感谢！！！
